apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: autopulse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:26.0
          args: ["start-dev"]
          ports:
            - containerPort: 8080
          env:
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: autopulse-secrets
                  key: KEYCLOAK_ADMIN_USERNAME
            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: autopulse-secrets
                  key: KEYCLOAK_ADMIN_PASSWORD
            - name: KC_HEALTH_ENABLED
              value: "true"
            - name: KC_DB
              value: postgres
            - name: KC_DB_URL
              value: jdbc:postgresql://psql-poland-autopulse-dev.postgres.database.azure.com:5432/autopulse?sslmode=require&currentSchema=keycloak
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: autopulse-secrets
                  key: KEYCLOAK_DB_USERNAME
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: autopulse-secrets
                  key: KEYCLOAK_DB_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: autopulse
spec:
  type: NodePort
  selector:
    app: keycloak
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30088
