services:
  vroom:
    image: vroomvrp/vroom-docker:v1.13.0
    container_name: vroom
    depends_on:
      - osrm
    volumes:
      - ./vroom-conf:/conf
    environment:
      - VROOM_ROUTER=osrm
    ports:
      - "3000:3000"
    networks:
      - routing-net

  osrm:
    image: osrm/osrm-backend
    container_name: osrm
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./osrm-data:/data
    command: >
      osrm-routed --max-matching-size 1000 --max-table-size 1000 --max-viaroute-size 1000 --algorithm mld /data/romania-latest.osrm
    networks:
      - routing-net

networks:
  routing-net:
    driver: bridge