server:
  port: ${SERVER_PORT:8085}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}?currentSchema=geography_service
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: ${DB_SCHEMA:geography_service}
        format_sql: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_ISSUER_URI:http://localhost:8008/realms/autopulse}

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false