package com.autopulse.parcelservice.model.enums;

public enum ParcelStatus {
    CREATED,

    SENDER_REGIONAL_COURIER_ASSIGNED,
    PICKED_UP_BY_SENDER_REGIONAL_COURIER,
    IN_SENDER_REGIONAL_DEPOSIT,

    TRANSIT_COURIER_ASSIGNED,
    IN_TRANSIT,

    IN_RECEIVER_REGIONAL_DEPOSIT,
    RECEIVER_REGIONAL_COURIER_ASSIGNED,
    IN_DELIVERY,

    DELIVERED,
    WAITING_IN_DEPOT
}
