spring.application.name=routing-service
server.port=${ROUTING_SERVER_PORT:8081}

spring.datasource.url=jdbc:postgresql://${ROUTING_DB_HOST}:${ROUTING_DB_PORT}/${DB_NAME}
spring.datasource.username=${ROUTING_USER}
spring.datasource.password=${ROUTING_USER_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=${ROUTING_SCHEMA}

eureka.client.enabled=true
spring.cloud.discovery.enabled=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka}
eureka.instance.prefer-ip-address=true

app.vroom.base-url=http://${VROOM_BASE_URL}:${VROOM_BASE_PORT}
app.vroom.request-output-dir=${VROOM_REQUEST_OUTPUT_DIR:target/vroom}

spring.security.oauth2.resourceserver.jwt.issuer-uri=${OAUTH2_ISSUER_URI:http://localhost:8008/realms/autopulse}

app.delivery-execution.base-url=${DELIVERY_EXECUTION_BASE_URL}

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}
