server.port=${ROUTING_SERVER_PORT:8081}

spring.datasource.url=${SPRING_DATASOURCE_URL}?currentSchema=routing_service
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=${ROUTING_SCHEMA}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

eureka.client.enabled=false
spring.cloud.discovery.enabled=false
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

app.vroom.base-url=http://localhost:3000
app.delivery-execution.base-url=${DELIVERY_EXECUTION_BASE_URL}