services:
  kafka:
    image: confluentinc/cp-kafka:8.2.0
    container_name: autopulse-kafka
    hostname: autopulse-kafka
    restart: unless-stopped
    ports:
      - "9092:9092"
    networks:
      - autopulse-network
    environment:
      CLUSTER_ID: ${KAFKA_CLUSTER_ID}
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://autopulse-kafka:29092,CONTROLLER://autopulse-kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://autopulse-kafka:29092,PLAINTEXT_HOST://localhost:9092

      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@autopulse-kafka:29093

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"

    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server autopulse-kafka:29092 --list >/dev/null 2>&1"]
      interval: 10s
      timeout: 10s
      retries: 12
      start_period: 20s

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: autopulse-kafka-ui
    restart: unless-stopped
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - "9100:8080"
    networks:
      - autopulse-network
    environment:
      KAFKA_CLUSTERS_0_NAME: autopulse-local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: autopulse-kafka:29092

networks:
  autopulse-network:
    external: true
    name: autopulse-network