apiVersion: apps/v1
kind: Deployment
metadata:
  name: routing-service
  namespace: autopulse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: routing-service
  template:
    metadata:
      labels:
        app: routing-service
    spec:
      containers:
        - name: routing-service
          image: crautopulsedev.azurecr.io/autopulse-routing-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8086
          envFrom:
            - configMapRef:
                name: autopulse-config
          env:
            - name: SERVER_PORT
              value: "8086"
            - name: ROUTING_SERVER_PORT
              value: "8086"
            - name: ROUTING_USER
              valueFrom:
                secretKeyRef:
                  name: autopulse-secrets
                  key: ROUTING_DB_USER
            - name: ROUTING_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: autopulse-secrets
                  key: ROUTING_DB_PASSWORD
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: autopulse-config
                  key: ROUTING_DB_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: autopulse-secrets
                  key: ROUTING_DB_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: autopulse-secrets
                  key: ROUTING_DB_PASSWORD
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              valueFrom:
                configMapKeyRef:
                  name: autopulse-config
                  key: OAUTH2_ISSUER_URI
            - name: VROOM_BASE_URL
              value: vroom
            - name: VROOM_BASE_PORT
              value: "3000"
            - name: DELIVERY_EXECUTION_BASE_URL
              value: http://delivery-execution-service:8081
---
apiVersion: v1
kind: Service
metadata:
  name: routing-service
  namespace: autopulse
spec:
  selector:
    app: routing-service
  ports:
    - port: 8086
      targetPort: 8086
